name: k_tech
description: "Aplikasi Monitoring Pabrik Kain - MES & CMMS"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  mobile_scanner: ^7.2.0
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  excel: ^4.0.6
  pdf: ^3.12.0
  path_provider: ^2.1.5
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
