// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0hJi04iuKN8bWm2fZrjD_EMfY1QAlh-E',
    appId: '1:971749839199:web:abcf5b8aec8921969166ea',
    messagingSenderId: '971749839199',
    projectId: 'prct-tekstil',
    authDomain: 'prct-tekstil.firebaseapp.com',
    storageBucket: 'prct-tekstil.firebasestorage.app',
    measurementId: 'G-3WQQ5C0E2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnvqdU3DcJwICUza588AJUtYS3rFhTJy0',
    appId: '1:971749839199:android:2751dac0c1ff0b349166ea',
    messagingSenderId: '971749839199',
    projectId: 'prct-tekstil',
    storageBucket: 'prct-tekstil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChwLb3umjPEavEc5UBggOnzVV-pM93Y7w',
    appId: '1:971749839199:ios:46c8ebcd9a93363d9166ea',
    messagingSenderId: '971749839199',
    projectId: 'prct-tekstil',
    storageBucket: 'prct-tekstil.firebasestorage.app',
    iosBundleId: 'com.example.kTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChwLb3umjPEavEc5UBggOnzVV-pM93Y7w',
    appId: '1:971749839199:ios:46c8ebcd9a93363d9166ea',
    messagingSenderId: '971749839199',
    projectId: 'prct-tekstil',
    storageBucket: 'prct-tekstil.firebasestorage.app',
    iosBundleId: 'com.example.kTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0hJi04iuKN8bWm2fZrjD_EMfY1QAlh-E',
    appId: '1:971749839199:web:0bab91fc9fcd90299166ea',
    messagingSenderId: '971749839199',
    projectId: 'prct-tekstil',
    authDomain: 'prct-tekstil.firebaseapp.com',
    storageBucket: 'prct-tekstil.firebasestorage.app',
    measurementId: 'G-XRFYL61KZD',
  );
}
